# name: SCS-HP Deploy on S3
# on:
#   push:
#       branches:
#         - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy  # S3にデプロイ 
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run:
#           aws s3 cp --recursive --region ap-northeast-1 s3://sottoproject30
#       - name: Upload to S3
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --acl public-read --follow-symlinks --delete
#           source_dir: ./dist/
#           bucket_url: s3://my-bucket-name
name: Upload to S3
#-------------------------#
# トリガー
#-------------------------#
on:
  #-- mainブランチにpushされたら起動する --#
  push:
      branches:
        - main

#-------------------------#
# 実際の処理
#-------------------------#
jobs:
  build:
    #-- 仮想マシンのOSを指定（ここではUbuntuの最新版） --#
    runs-on: ubuntu-latest
    steps:
      #-- Gitリポジトリの内容を取得 --#
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to S3
        #-- GitHub上に登録した変数を持ってくる --#
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #-- 仮想マシン上でコマンドを実行 --#
        run:
          aws s3 sync --delete --region ap-northeast-1 ./img s3://sottoproject30/
